### PR TITLE
Update live_basecalling.md

### PR DESCRIPTION
**Pull request by lpryszcz**
systemd service need to be enabled before it can be started

### CODE REVIEW

**Review by sirselim — COMMENTED** [review]
If you are happy to change the first line "Before..." with "We also want to enable this service to auto start upon a system restart:" then I will happily merge the PR.

**Comment by lpryszcz** [comment]
done. 
please note, that without enabling the service, you can't start it manually or with system restart - systemd doesn't see it until you enable it.

**Comment by sirselim** [comment]
Thanks for amending that.

> please note, that without enabling the service, you can't start it manually or with system restart - systemd doesn't see it until you enable it.

That's not the case, running `systemctrl start guppyd.service` will work just fine after adding `guppyd.service` to the appropriate location. You can see this from screen shots and terminal dumps in my notes. All the enabling is doing is telling systemd to start that service automatically upon boot/launching the OS. What you describe doesn't make sense, otherwise you couldn't have services manually controlled - everything would have to be 'enabled', meaning it would launch automatically. A user might not want that from all services. Why have `start` if you have to use `enable`?

The Fedora Project docs ([here](https://docs.fedoraproject.org/en-US/quick-docs/understanding-and-administering-systemd/#starting-stopping-and-querying-systemd-services)) break it down, but I think [the top answer to this Stackoverflow question](https://askubuntu.com/questions/733469/what-is-the-difference-between-systemctl-start-and-systemctl-enable) sums it up nicely:

> `systemctl start` and `systemctl enable` do different things.
>
> `enable` will hook the specified unit into relevant places, so that it will automatically start on boot, or when relevant hardware is plugged in, or other situations depending on what's specified in the unit file.
> 
> `start` starts the unit right now.
> 
> `disable` and `stop` are the opposite of these, respectively.
> 
> This means that when you first install MariaDB, you might want to run `systemctl enable mariadb.service` to enable it so it starts on boot. You might also want to run `systemctl start mariadb.service`, or just reboot, in order to start MariaDB. To stop MariaDB, run `systemctl stop mariadb.service` (it will start again on next boot or when you manually start it). To disable it so it doesn't start on boot anymore, run `systemctl disable mariadb.service`.

**Comment by lpryszcz** [comment]
Completely agree with you. 

Just to clarify, in the protocol, you are starting the service using `sudo service guppyd start` or `systemctl start guppyd.service`. You will get an error with the former (this was my case) if you don't enable the service (`systemctl enable guppyd.service`) before. But you're right, the latter should work without enabling the service. 

Cheers!

**Pull request merged**
